apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-mellomlagring
  namespace: dusseldorf
  labels:
    team: dusseldorf
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  gcp:
    buckets:
      - name: {{ bucket.name }}
        lifecycleCondition:
          age: {{ bucket.objectAge }}
  accessPolicy:
    inbound:
      rules:
        - application: k9-brukerdialog-api
        - application: k9-brukerdialog-prosessering
        - application: k9-joark
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: clamav
          namespace: nais-system
  env:
    - name: BASE_URL
      value: http://k9-mellomlagring
    - name: VIRUS_SCAN_URL
      value: http://clamav.nais-system/scan
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: k9-mellomlagring.crypto
