apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  gcp:
    buckets:
      - name: {{ bucket.name }}
        lifecycleCondition:
          age: {{ bucket.objectAge }}

  accessPolicy:
    inbound:
      rules:
        - application: omsorgspenger-midlertidig-alene-prosessering
        - application: omsorgsdager-melding-api
        - application: omsorgspenger-api
        - application: omsorgspengesoknad-prosessering
        - application: k9-ettersending-api
        - application: k9-ettersending-prosessering
        - application: omsorgspengerutbetaling-api
        - application: omsorgspengerutbetalingsoknad-arbeidstaker-api
        - application: omsorgsdager-melding-prosessering
        - application: omsorgsdager-aleneomsorg-prosessering
        - application: pleiepengesoknad-api
        - application: pleiepenger-livets-sluttfase-api
        - application: pleiepenger-livets-sluttfase-prosessering
        - application: k9-joark
          namespace: {{namespace}}
          cluster: {{fss-cluster}}
        - application: omsorgspengerutbetalingsoknad-prosessering
          namespace: {{namespace}}
          cluster: {{fss-cluster}}
        - application: omsorgspengerutbetalingsoknad-arbeidstaker-prosessering
          namespace: {{namespace}}
          cluster: {{fss-cluster}}
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: clamav
          namespace: clamav
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
  envFrom:
    - secret: k9-mellomlagring.crypto
    - configmap: loginservice-idporten
